routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app)
from werkzeug.datastructures import FileStorage

from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, cache
# from routes import current_user

import json

from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""

# import gevent
import time



@main.route("/")
def index():
    # t = threading.Thread()
    # t.start()
    # gevent.spawn()

    print('time type')

    # print('time type', time.sleep, gevent.sleep)

    return render_template("user_login.html")


@main.route("/resume")
def resume():
    return render_template("resume.html")


@main.route("/register_view")
def register_view():

    return render_template("user_regiser.html")

@main.route("/forget_pwd")
def forget_pwd():

    return render_template("forget_pwd.html")


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login user <{}>'.format(u))
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        log('index login key <{}> user_id <{}>'.format(key, u.id))
        cache.set(key, u.id)

        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        return response
        # session['user_id'] = u.id
        # return redirect(url_for('topic.index'))


def created_topic(user_id):
    # O(n)
    ts = Topic.all(user_id=user_id)

    return ts
    #
    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # O(k)+O(m*n)
    # rs = Reply.all(user_id=user_id)
    # ts = []
    # for r in rs:
    #     t = Topic.one(id=r.topic_id)
    #     ts.append(t)
    # return ts
    #
    #     sql = """
    # select * from topic
    # join reply on reply.topic_id=topic.id
    # where reply.user_id=1
    # """
    # k = 'replied_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     # ts = Topic.select()
    #     #   .join(Reply, 'id', 'topic_id')
    #     #   .where(user_id=user_id)
    #     #   .all()
    #     rs = Reply.all(user_id=user_id)
    #     ts = []
    #     for r in rs:
    #         t = Topic.one(id=r.topic_id)
    #         ts.append(t)
    #
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #
    #     return ts
    ts = Topic.query\
        .join(Reply, Topic.id == Reply.topic_id)\
        .filter(Reply.user_id == user_id)\
        .all()
    return ts


@main.route('/setting')
def setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:

        return render_template(
            'setting.html',
            user=u,
        )


@main.route('/setting/change', methods=['POST'])
def setting_change():
    form = request.form.to_dict()
    u = current_user()
    username = form['username']
    quote = form['quote']
    User.update(u.id, username=username, quote=quote)

    return redirect(url_for('.setting'))


@main.route('/setting/pwd_change', methods=['POST'])
def setting_pwd_change():
    form = request.form.to_dict()
    u = current_user()
    old_pass = form['old_pass']
    if u.password == User.salted_password(old_pass):
        new_pass = User.salted_password(form['new_pass'])

        User.update(u.id, password=new_pass)
    else:
        print('mimacuowu')

    return redirect(url_for('.setting'))


@main.route('/user/<name>')
def user_index(name):
    u = User.one(username=name)
    if u is None:
        abort(404)
    else:
        tss= Topic.all(user_id=u.id)
        ts = sorted(tss, key=lambda s: s.created_time, reverse=True)

        rs = Reply.all(user_id=u.id)
        rtss = []
        for r in rs:
            rtss.append(Topic.one(id=r.topic_id))
        rts = sorted(rtss, key=lambda s: s.created_time, reverse=True)

        return render_template('user_index.html', user=u, topics=ts, rtopics=rts)


@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('static/images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='/static/images/{}'.format(filename))

        return redirect(url_for('.setting'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:3000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)

routes/reset_pwd.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.message import Messages
from routes import *

main = Blueprint('reset', __name__)



@main.route('/send', methods=['POST'])
def reset_send():
    form = request.form.to_dict()
    username = form['username']
    u = User.one(username=username)
    token = str(uuid.uuid4())
    cache.set(token, u.id)
    # csrf_tokens[token] = u.id

    link = 'https://www.fengfan620.com/reset/view?token={}'.format(token)
    Messages.send(
        title='小破站重置密码',
        content='点击链接重置密码啦~~点击<br>{}'.format(link),
        sender_id=1,
        receiver_id=u.id
    )
    return redirect(url_for('index.index'))


@main.route('/view')
def reset_view():
    token = request.args.get('token')
    if token is not None:
        return render_template('reset_pwd.html', token=token)


@main.route('/view/update', methods=['POST'])
def reset_update():
    form = request.form.to_dict()
    password = User.salted_password(form['password'])
    token = str(form['token'])

    if token is not None:
        # id = csrf_tokens[token]
        id = cache.get(token)
        User.update(id, password=password)
    return redirect(url_for('index.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.base_model import db
from models.reply import Reply
from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    user=current_user()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, user=user,bid=board_id)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    log('删除 topic 用户是', u, id)
    # t.username = 'udade'
    # Topic.delete(id)
    # for reply in Reply.all(topic_id=id):
    #     Reply.delete(reply.id)
    # m = cls.query.filter_by(id=id).first()
    # db.session.delete(m)
    try:
        Topic.query.filter_by(id=id).delete()
        # raise Exception('垃圾异常')
        Reply.query.filter_by(topic_id=id).delete()
        db.session.commit()
    except Exception:
        db.session.rollback()
    # 删除帖子和所有十条回复
    # 删除了帖子和三条回复
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()

    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/forget_pwd.html
<!DOCTYPE html>
<!-- saved from url=(0048)https://amazeui.clouddeep.cn/examples/login.html -->
<html><head lang="en"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <title>Login Page | Amaze UI Example</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp">
  <link rel="alternate icon" type="image/png" href="https://amazeui.clouddeep.cn/i/favicon.png">
  <link rel="stylesheet" href="../Login%20Page%20_%20Amaze%20UI%20Example_files/amazeui.min.css">
    <link rel="stylesheet" href="../static/css/amazeui.min.css">
  <style>
    .header {
      text-align: center;
    }
    .header h1 {
      font-size: 200%;
      color: #333;
      margin-top: 30px;
    }
    .header p {
      font-size: 14px;
    }

  </style>
</head>
<body>
<div class="header">
  <div class="am-g">
    <h1>重置密码</h1>

  </div>
  <hr>
</div>
<div class="am-g">
  <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">




    <form method="post" class="am-form" method="post" method="post" action="{{ url_for('reset.reset_send') }}">
      <label for="email">用户名:</label>
      <input type="text" name="username" id="username" value="" autocomplete="off" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;" >

      <br>
        <h3>我们将会发送邮件至您注册是的邮箱来重置密码</h3>
      <div class="am-cf">
        <input type="submit" name="" value="重置密码" class="am-btn am-btn-primary am-btn-sm am-fl">


      </div>
    </form>
    <hr>

  </div>
</div>


</body></html>

templates/profile.html
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock %}
{% block main %}
<h1>我的主页</h1>
<div id="main">
    <div id="sidebar">

        <div class="panel">

            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for('index.user_index', name=user.username) }}">
                            <img src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name"><a class="dark"
                                                   href="{{ url_for('index.user_index', name=user.username) }}">{{ user.username }}</a></span>

                        <div class="board clearfix">
                            <div class="floor">
                                <span class="big">积分: 0 </span>
                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
        “

            {{ user.quote }}

        ”
    </span>
                    </div>
                </div>


            </div>

        </div>

    </div>

    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('topic.index') }}">主页</a><span class="divider">/</span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src={{ user.image }} class="user_avatar"
                         title="{{ user.username }}">
                </div>
                <a class="dark">{{ user.username }}</a>

                <p class="col_fade">{{ user.created_time | format_time}}</p>

            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>

            {% for t in created %}
                <div class="cell">

                    <a class="user_avatar pull-left" href="{{ url_for('index.user_index', name=user.username) }}">
                        <img src="{{ t.user().image }}" title="{{ t.user_id }}">
                    </a>

                    <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                      {{ t.replies() | count }}
                    </span>
                    <span class="count_seperator">/</span>
                    <span class="count_of_visits" title="点击数">
                      {{ t.views }}
                    </span>
                  </span>
                    <a class="last_time pull-right"
                       href="">

                        <span class="last_active_time">{{ t.created_time | format_time}}</span>
                    </a>


                    <div class="topic_title_wrapper">


                        <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}" title="{{ t.title }}">
                            {{ t.title }}
                        </a>
                    </div>
                </div>

            {% endfor %}


        </div>


        <div class="panel">
            <div class="header">
                <span class="col_fade">最近参与的话题</span>
            </div>
            <div>
                {% for r in replied %}
                    <div class="cell">

                        <a class="user_avatar pull-left" href="{{ url_for('index.user_index', name=user.username) }}">
                            <img src="{{ r.user().image }}" title="{{ r.user_id }}">
                        </a>

                        <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                          {{ r.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                          {{ r.views }}
                        </span>
                      </span>
                            <span class="last_active_time">{{ r.created_time | format_time}}</span>
                        </a>


                        <div class="topic_title_wrapper">


                            <a class="topic_title" href="{{ url_for('topic.detail', id=r.id) }}"
                               title="{{ r.title }}">
                                {{ r.title }}
                            </a>
                        </div>
                    </div>

                {% endfor %}


            </div>


        </div>


    </div>

</div>

    <div>
        <img src="{{ user.image }}" alt="" style="    width: 300px;
    height: 270px;">
        <form method="post" action="{{ url_for('.avatar_add') }}" enctype="multipart/form-data">
            <input type="file" name="avatar">
            <button type="submit" class="span-primary submit_btn">上传头像</button>
        </form>
    </div>
{% endblock %}

templates/reset_pwd.html
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock %}
{% block main %}
<div><br>
    <br>
    <br>
    <br>
    <br>
</div>
<form action="{{ url_for('reset.reset_update') }}" method="POST">
    <input type="text" name="password">
    <input type="text" name="token" value="{{ token }}" style="display:None">

    <button type="submit">确定</button>
</form>

{% endblock %}

templates/setting.html
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock %}
{% block main %}
    <div id="sidebar">

        <div class="panel">
<div class="header">
                <span class="col_fade">~</span>
            </div>
            <div class="header">
                <span class="col_fade"></span>
            </div>
            <div class="header">
                <span class="col_fade" style="font-size: 25px;">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for('index.user_index', name=user.username) }}">
                            <img src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name"><a class="dark"
                                                   href="{{ url_for('index.user_index', name=user.username) }}">{{ user.username }}</a></span>

                        <div class="board clearfix">
                            <div class="floor">

                            </div>
                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
        “

            {{ user.quote }}

        ”
    </span>
                    </div>
                </div>


            </div>

        </div>

    </div>

    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('.index') }}">主页</a><span class="divider">/</span></li>
                    <li class="active">设置</li>
                </ul>
            </div>
            <div class="inner">


                <form id="setting_form" class="form-horizontal" action="{{ url_for('.setting_change') }}" method="post"
                      _lpchecked="1">
                    <div class="control-group">
                        <label class="control-label" for="name">用户名</label>


                        <div class="controls">
                            <input class="input-xlarge" id="name" name="username" size="30" type="text">
                        </div>
                    </div>


                    <div class="control-group">
                        <label class="control-label" for="signature">个性签名</label>

                        <div class="controls">
                            <textarea class="input-xlarge" id="signature" name="quote" size="30"></textarea>
                        </div>
                    </div>


                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                    </div>
                </form>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">更改密码</span>
            </div>
            <div class="inner">
                <form id="change_pass_form" class="form-horizontal" action="{{ url_for(".setting_pwd_change") }}"
                      method="post">
                    <div class="control-group">
                        <label class="control-label" for="old_pass">当前密码</label>

                        <div class="controls">
                            <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="new_pass">新密码</label>

                        <div class="controls">
                            <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
                        </div>
                    </div>
                    <input type="hidden" id="action" name="action" value="change_password">
                    <input type="hidden" name="_csrf" value="QXyHGB86-XD-ptk2Q6EThblp8qEPEaQXdVXo">

                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div>
        <img src="{{ user.image }}" alt="" style="    width: 300px;
    height: 270px;">
        <form method="post" action="{{ url_for('.avatar_add') }}" enctype="multipart/form-data">
            <input type="file" name="avatar">
            <button type="submit" class="span-primary submit_btn">上传头像</button>
        </form>
    </div>

{% endblock %}

templates/user_index.html
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock %}
{% block main %}
<div id="main">


    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('topic.index') }}">主页</a><span class="divider">/</span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src={{ user.image }} class="user_avatar"
                         title="{{ user.username }}">
                </div>
                <a class="dark">{{ user.username }}</a>

                <p class="col_fade">{{ user.created_time | format_time}}</p>

            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>

            {% for t in topics %}
                <div class="cell">

                    <a class="user_avatar pull-left" href="{{ url_for('index.user_index', name=t.user().username) }}">
                        <img src="{{ t.user().image }}" title="{{ t.user_id }}">
                    </a>

                    <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                      {{ t.replies() | count }}
                    </span>
                    <span class="count_seperator">/</span>
                    <span class="count_of_visits" title="点击数">
                      {{ t.views }}
                    </span>
                  </span>
                    <a class="last_time pull-right"
                       href="">
                        <img class="user_small_avatar" src="{{ url_for('static', filename='img/fan.jpg') }}">
                        <span class="last_active_time">{{ t.created_time | format_time}}</span>
                    </a>


                    <div class="topic_title_wrapper">


                        <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}" title="{{ t.title }}">
                            {{ t.title }}
                        </a>
                    </div>
                </div>

            {% endfor %}


        </div>


        <div class="panel">
            <div class="header">
                <span class="col_fade">最近参与的话题</span>
            </div>
            <div>
                {% for r in rtopics %}
                    <div class="cell">

                        <a class="user_avatar pull-left" href="{{ url_for('index.user_index', name=r.user().username) }}">
                            <img src="{{ r.user().image }}" title="{{ r.user_id }}">
                        </a>

                        <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                          {{ r.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                          {{ r.views }}
                        </span>
                      </span>
                        <a class="last_time pull-right"
                           href="https://cnodejs.org/topic/5cc7a5b105ae566f637fdb7c#5cc7ae24a86ae80ce64b5917">
                            <img class="user_small_avatar" src="{{ url_for('static', filename='img/fan.jpg') }}">
                            <span class="last_active_time">{{ r.created_time | format_time}}</span>
                        </a>


                        <div class="topic_title_wrapper">


                            <a class="topic_title" href="{{ url_for('topic.detail', id=r.id) }}"
                               title="{{ r.title }}">
                                {{ r.title }}
                            </a>
                        </div>
                    </div>

                {% endfor %}


            </div>


        </div>


    </div>

</div>

{% endblock %}

templates/user_login.html
<!DOCTYPE html>
<!-- saved from url=(0048)https://amazeui.clouddeep.cn/examples/login.html -->
<html><head lang="en"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  
  <title>Login Page | Amaze UI Example</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp">
  <link rel="alternate icon" type="image/png" href="https://amazeui.clouddeep.cn/i/favicon.png">
  <link rel="stylesheet" href="../Login%20Page%20_%20Amaze%20UI%20Example_files/amazeui.min.css">
    <link rel="stylesheet" href="../static/css/amazeui.min.css">
  <style>
    .header {
      text-align: center;
    }
    .header h1 {
      font-size: 200%;
      color: #333;
      margin-top: 30px;
    }
    .header p {
      font-size: 14px;
    }

  </style>
</head>
<body>
<div class="header">
  <div class="am-g">
    <h1>登录</h1>

  </div>
  <hr>
</div>
<div class="am-g">
  <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">




    <form method="post" class="am-form" method="post" action="{{ url_for('.login') }}">
      <label for="email">用户名:</label>
      <input type="text" name="username" id="username" value="taylor" autocomplete="off" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;" onblur="if(this.value == '')this.value='taylor';" onclick="if(this.value == 'taylor')

this.value='';" />
      <br>
      <label for="password">密码:</label>
      <input type="password" name="password" id="password" value="123" autocomplete="off" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;" onblur="if(this.value == '')this.value='123';" onclick="if(this.value == '123')

this.value='';" />
      <br>
        <div>
        </div>

      <br>
      <div class="am-cf">
        <input type="submit" name="" value="登 录" class="am-btn am-btn-primary am-btn-sm am-fl">
                        <a href="{{ url_for("index.forget_pwd") }}" name="" value=" " class="am-btn am-btn-default am-btn-sm am-fl">忘记密码 ^_^?</a>

            <a href="{{ url_for('index.register_view') }}" name="" value="注册" class="am-btn am-btn-primary am-btn-sm am-fr">注册</a>

      </div>
    </form>
    <hr>

  </div>
</div>
<footer style="height:50px;position:fixed;left:43%;bottom:0px; text-align: center;">

        备案：苏ICP备19037148号-1

</footer>



</body></html>