models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app)
from werkzeug.datastructures import FileStorage

from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, cache
# from routes import current_user

import json

from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""

# import gevent
import time



@main.route("/")
def index():
    # t = threading.Thread()
    # t.start()
    # gevent.spawn()

    print('time type')

    # print('time type', time.sleep, gevent.sleep)

    return render_template("user_login.html")


@main.route("/resume")
def resume():
    return render_template("resume.html")


@main.route("/register_view")
def register_view():

    return render_template("user_regiser.html")

@main.route("/forget_pwd")
def forget_pwd():

    return render_template("forget_pwd.html")


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    print('login user <{}>'.format(u))
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        log('index login key <{}> user_id <{}>'.format(key, u.id))
        cache.set(key, u.id)

        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        return response
        # session['user_id'] = u.id
        # return redirect(url_for('topic.index'))


def created_topic(user_id):
    # O(n)
    ts = Topic.all(user_id=user_id)

    return ts
    #
    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # O(k)+O(m*n)
    # rs = Reply.all(user_id=user_id)
    # ts = []
    # for r in rs:
    #     t = Topic.one(id=r.topic_id)
    #     ts.append(t)
    # return ts
    #
    #     sql = """
    # select * from topic
    # join reply on reply.topic_id=topic.id
    # where reply.user_id=1
    # """
    # k = 'replied_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     # ts = Topic.select()
    #     #   .join(Reply, 'id', 'topic_id')
    #     #   .where(user_id=user_id)
    #     #   .all()
    #     rs = Reply.all(user_id=user_id)
    #     ts = []
    #     for r in rs:
    #         t = Topic.one(id=r.topic_id)
    #         ts.append(t)
    #
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #
    #     return ts
    ts = Topic.query\
        .join(Reply, Topic.id == Reply.topic_id)\
        .filter(Reply.user_id == user_id)\
        .all()
    return ts


@main.route('/setting')
def setting():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:

        return render_template(
            'setting.html',
            user=u,
        )


@main.route('/setting/change', methods=['POST'])
def setting_change():
    form = request.form.to_dict()
    u = current_user()
    username = form['username']
    quote = form['quote']
    User.update(u.id, username=username, quote=quote)

    return redirect(url_for('.setting'))


@main.route('/setting/pwd_change', methods=['POST'])
def setting_pwd_change():
    form = request.form.to_dict()
    u = current_user()
    old_pass = form['old_pass']
    if u.password == User.salted_password(old_pass):
        new_pass = User.salted_password(form['new_pass'])

        User.update(u.id, password=new_pass)
    else:
        print('mimacuowu')

    return redirect(url_for('.setting'))


@main.route('/user/<name>')
def user_index(name):
    u = User.one(username=name)
    if u is None:
        abort(404)
    else:
        tss= Topic.all(user_id=u.id)
        ts = sorted(tss, key=lambda s: s.created_time, reverse=True)

        rs = Reply.all(user_id=u.id)
        rtss = []
        for r in rs:
            rtss.append(Topic.one(id=r.topic_id))
        rts = sorted(rtss, key=lambda s: s.created_time, reverse=True)

        return render_template('user_index.html', user=u, topics=ts, rtopics=rts)


@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('static/images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='/static/images/{}'.format(filename))

        return redirect(url_for('.setting'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:3000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)

routes/message.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.message import Messages
main = Blueprint('mail', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    receiver_id = int(form['receiver_id'])
    # 发邮件
    Messages.send(
        title=form['title'],
        content=form['content'],
        sender_id=u.id,
        receiver_id=receiver_id
    )

    return redirect(url_for('.index'))


@main.route('/')
def index():
    u = current_user()

    send = Messages.all(sender_id=u.id)
    received = Messages.all(receiver_id=u.id)

    t = render_template(
        'mail/index.html',
        send=send,
        received=received,
        user=u
    )
    return t


@main.route('/view/<int:id>')
def view(id):
    message = Messages.one(id=id)
    u = current_user()
    # if u.id == mail.receiver_id or u.id == mail.sender_id:
    if u.id in [message.receiver_id, message.sender_id]:
        return render_template('mail/detail.html', message=message,user=u)
    else:
        return redirect(url_for('.index'))

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    Request)

from models.message import Messages
from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


def users_from_content(content):
    # 内容 @123 内容
    # 如果用户名含有空格 就不行了 @name 123
    # 'a b c' -> ['a', 'b', 'c']
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_mails(sender, receivers, reply_link, reply_content):
    print('send_mail', sender, receivers, reply_content)
    content = '链接：{}\n内容：{}'.format(
        reply_link,
        reply_content
    )
    for r in receivers:
        title = '你被 {} AT 了'.format(sender.username)
        Messages.send(
            title=title,
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()

    content = form['content']
    users = users_from_content(content)
    send_mails(u, users, request.referrer, content)

    form = form.to_dict()
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.base_model import db
from models.reply import Reply
from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    user=current_user()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, user=user,bid=board_id)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    log('删除 topic 用户是', u, id)
    # t.username = 'udade'
    # Topic.delete(id)
    # for reply in Reply.all(topic_id=id):
    #     Reply.delete(reply.id)
    # m = cls.query.filter_by(id=id).first()
    # db.session.delete(m)
    try:
        Topic.query.filter_by(id=id).delete()
        # raise Exception('垃圾异常')
        Reply.query.filter_by(topic_id=id).delete()
        db.session.commit()
    except Exception:
        db.session.rollback()
    # 删除帖子和所有十条回复
    # 删除了帖子和三条回复
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()

    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
<link rel="stylesheet" href="//cdnjs.loli.net/ajax/libs/mdui/0.4.3/css/mdui.min.css">
<head>
<body>
<div class="mdui-appbar mdui-appbar-fixed .mdui-appbar-scroll-hide">
  <div class="mdui-toolbar mdui-color-cyan-800">
    <a href="{{ url_for('topic.index') }}" class="mdui-btn mdui-ripple" style="font-size: 19px;">首页</a>
    <div class="mdui-toolbar-spacer"></div>
      <a href="{{ url_for("index.profile") }}" class="mdui-btn mdui-ripple" style="font-size: 19px;">个人主页</a>
    <a href="{{ url_for('index.setting') }}" class="mdui-btn mdui-ripple" style="font-size: 19px;">用户设置</a>
    <a href="{{ url_for('mail.index') }}" class="mdui-btn mdui-ripple" style="font-size: 19px;">站内信</a>
    <a href='{{ url_for('index.register_view') }}' class="mdui-btn mdui-ripple" style="font-size: 19px;">注册</a>
    <a href='{{ url_for('index.index') }}' class="mdui-btn mdui-ripple" style="font-size: 19px;">登录</a>

  </div>
</div>

{#<!-- navbar -->#}
{#<div class='navbar'>#}
{#  <div class='navbar-inner'>#}
{#    <div class='container'>#}
{#      <ul class='nav pull-right'>#}
{#        <li><a href='{{ url_for('topic.index') }}'>首页</a></li>#}
{##}
{#        <li><a href='{{ url_for('index.setting') }}'>个人设置</a></li>#}
{#        <li><a href='/api'>API</a></li>#}
{##}
{#        <li><a href="/about" target="">关于</a></li>#}
{##}
{##}
{#        <li><a href='{{ url_for('index.index') }}'>注册</a></li>#}
{#        <li><a href='{{ url_for('index.index') }}'>登录</a></li>#}
{##}
{#      </ul>#}
{#      <a class="btn btn-navbar" id="responsive-sidebar-trigger">#}
{#        <span class="icon-bar"></span>#}
{#        <span class="icon-bar"></span>#}
{#        <span class="icon-bar"></span>#}
{#      </a>#}
{#    </div>#}
{#  </div>#}
{#</div>#}
<script src="//cdnjs.loli.net/ajax/libs/mdui/0.4.3/js/mdui.min.js"></script>
{% block main %}
{% endblock %}


</body>

templates/topic/detail.html
{% extends "topic/base.html" %}
{% block title %}{{ topic.title }}{% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 2 天前
            </span>
                    <span>
                {% set u = topic.user() %}
                作者 {{ u.username }}
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content}}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ u.username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 / {{ loop.length }}楼 •
                            <span>{{ r.created_time }}</span>
                        </a>
                    </div>
                    <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ r.content }}</div>

                </div>
            </div>
        {% endfor %}
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</div>


<link rel="stylesheet" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/style.css">
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> lanage 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var __main = function () {
        markContents()
        highlight()
    }

    __main()

</script>

{% endblock %}

templates/topic/index.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--<meta charset="UTF-8">-->
<!--<title>bbs club</title>-->
<!--<link rel="stylesheet" href="/static/css/bootstrap.min.css">-->
<!--<link rel="stylesheet" href="/static/css/style.css">-->
<!--</head>-->
<!--<body>-->
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock %}
{% block main %}

    <div id="main">
        <div id="sidebar">

            <div class="panel">
                <div class="header">
                    <span class="col_fade">~</span>
                </div>
                <div class="header">
                    <span class="col_fade"></span>
                </div>
                <div class="header">
                    <span class="col_fade" style="font-size: 25px;">个人信息</span>
                </div>
                <div class="inner">
                    <div class="user_card">
                        <div>
                            <a class="user_avatar" href="{{ url_for('index.user_index', name=user.username) }}">
                                <img src="{{ user.image }}" title="{{ user.username }}">
                            </a>
                            <span class="user_name"><a class="dark"
                                                       href="{{ url_for('index.user_index', name=user.username) }}">{{ user.username }}</a></span>

                            <div class="board clearfix">
                                <div class="floor">

                                </div>
                            </div>
                            <div class="space clearfix"></div>
                            <span class="signature">
        “

            {{ user.quote }}

        ”
    </span>
                        </div>
                    </div>


                </div>

            </div>
            <div class="panel">
                <div class="inner">
                    <a href="{{ url_for('topic.new' ,board_id=bid) }}" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                {#        <div class="header">#}
                {##}
                {#        <a href="https://cnodejs.org/?tab=all" class="topic-tab ">全部</a>#}
                {##}
                {#        <a href="https://cnodejs.org/?tab=good" class="topic-tab ">精华</a>#}
                {##}
                {#        <a href="https://cnodejs.org/?tab=share" class="topic-tab ">分享</a>#}
                {##}
                {#        <a href="https://cnodejs.org/?tab=ask" class="topic-tab ">问答</a>#}
                {##}
                {#        <a href="https://cnodejs.org/?tab=job" class="topic-tab ">招聘</a>#}
                {##}
                {#        <a href="https://cnodejs.org/?tab=dev" class="topic-tab ">客户端测试</a>#}
                {##}
                {#    </div>#}
                <div class="header" style="  padding: 66px 35px;    font-size: 22.5px;">
                    <a href="/topic"
                       class="topic-tab current-tab">
                        all
                    </a>

                    {% for b in bs %}
                        <a href="/topic?board_id={{ b.id }}"
                           class="topic-tab current-tab">
                            {{ b.title }}
                        </a>
                    {% endfor %}
                </div>
                <div class="inner post" style=" line-height: 4em">
                    <div class="topic_list">
                        {% for t in ms %}
                            <div class="cell">
                                <div class="topic_title_wrapper">
                                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                        {{ t.title }}
                                    </a>
                                    <span>{{ t.replies() | count }} / {{ t.views }}</span>
                                    <!--<a class="topic_title" href="{{ url_for('topic.delete', id=t.id) }}">-->
                                    <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                        删除
                                    </a>

                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();

    </script>

{% endblock %}


<!--</body>-->
<!--</html>-->

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
<!--<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">-->
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            {% for b in bs %}
                {% if bid == b.id %}
                    <option value="{{ b.id }}" selected >{{ b.title }}</option>
                {% else %}
                    <option value="{{ b.id }}" >{{ b.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>